# -*- coding: utf-8 -*-
"""Data structure code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYzT4o4ow_q1qOK_JoRm9txel5jlKnMb

Write a code to create a tuple with the elements 100, 200, 300 and print it.
"""

tuple= (100,200,300)
print(tuple)

""" Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow')."""

# we can use negative indexing here because it is starts fromm the last element.
tuple= ('red','green','blue', 'yellow')
second_to_last_element= tuple[-2]
print(second_to_last_element)

"""Write a code to find the minimum number in the tuple (10, 20, 5, 15)"""

tuple = (10, 20, 5, 15)
min (tuple)

""" Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit')."""

tuple= ('dog','cat','rabbit')
tuple.index('cat')

"""Write a code to create a tuple containing three different fruits and check if "kiwi" is in it."""

tuple= ('kiwi', 'mango', 'banana')
'kiwi' in tuple

"""Write a code to create a set with the elements 'a', 'b', 'c' and print it."""

s= {'a', 'b', 'c'}
print(s)

"""Write a code to clear all elements from the set {1, 2, 3, 4, 5}.


"""

s= {1, 2, 3, 4, 5}
s.clear()
print(s)

"""Write a code to remove the element 4 from the set {1, 2, 3, 4}."""

s= {1, 2, 3, 4}
s.remove(4)
print(s)

"""Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}."""

set1 = {1, 2, 3}
set2 = {3, 4, 5}
union_set = set1.union(set2)
print(union_set)

"""Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}"""

set1 = {1, 2, 3}
set2 = {2, 3, 4}
intersection_set = set1.intersection(set2)
print(intersection_set)

"""Write a code to create a dictionary with the keys "name", "age", and "city", and print it"""

d = {'name': 'anu', 'age':'25', 'city':'nagpur'}
a = list(d.keys())
print(a)

"""Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}."""

d = {'name': 'John', 'age': 25}
d["country"] = "USA"
print(d)

"""Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}"""

d = {'name': 'Alice', 'age': 30}
d ['name']

""" Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}."""

d = {'name': 'Bob', 'age': 22, 'city': 'New York'}
del d['age']
d

"""Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}."""

# method 1:

data =  {'name': 'Alice', 'city': 'Paris'}

if 'city' in data:
  print ("the key 'city' exists in the dictionary")
else:
  print ("the key 'city' does not exist in the dictionary")

# method 2.
d = {'name': 'Alice', 'city': 'Paris'}

if 'city' in d.keys():
    print("The key 'city' exists in the dictionary.")
else:
    print("The key 'city' does not exist in the dictionary.")

"""Write a code to create a list, a tuple, and a dictionary, and print them all."""

d = {'name': ['Ram', 'Shyam','1','2'], 'email': 'aj@hmail.com', 'contact': (12345, 789) }

d

"""Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the result.(replaced)\"""

import random

random_numbers = [random.randint(1, 100) for _ in range(5)]

# Sort the list in ascending order
random_numbers.sort()

# Print the sorted list
print(random_numbers)

"""Write a code to create a list with strings and print the element at the third index"""

my_list = ["apple", "banana", "cherry", "date", "berry"]

print(my_list[3])

""" Write a code to combine two dictionaries into one and print the result."""

data = {'name': 'Alice', 'city': 'Paris'}
data2 = {'email': 'aj@hmail.com'}
data.update(data2)
data

"""Write a code to convert a list of strings into a set."""

d = ['ajay','anam','naman']
d = set(d)
type (d)